repos:
  - repo: local
    hooks:
      - id: autodocs
        name: autodocs
        entry: lua autodocs.lua . readme.md
        language: system
        pass_filenames: false
        always_run: true
